#pragma once
#include "mcString.h"
#include "varData.h"
#include "endian.h"

enum EntityType
{
	minecraft_area_effect_cloud = 0,
	minecraft_armor_stand = 1,
	minecraft_arrow = 2,
	minecraft_axolotl = 3,
	minecraft_bat = 4,
	minecraft_bee = 5,
	minecraft_blaze = 6,
	minecraft_boat = 7,
	minecraft_cat = 8,
	minecraft_cave_spider = 9,
	minecraft_chicken = 10,
	minecraft_cod = 11,
	minecraft_cow = 12,
	minecraft_creeper = 13,
	minecraft_dolphin = 14,
	minecraft_donkey = 15,
	minecraft_dragon_fireball = 16,
	minecraft_drowned = 17,
	minecraft_elder_guardian = 18,
	minecraft_end_crystal = 19,
	minecraft_ender_dragon = 20,
	minecraft_enderman = 21,
	minecraft_endermite = 22,
	minecraft_evoker = 23,
	minecraft_evoker_fangs = 24,
	minecraft_experience_orb = 25,
	minecraft_eye_of_ender = 26,
	minecraft_falling_block = 27,
	minecraft_firework_rocket = 28,
	minecraft_fox = 29,
	minecraft_ghast = 30,
	minecraft_giant = 31,
	minecraft_glow_item_frame = 32,
	minecraft_glow_squid = 33,
	minecraft_goat = 34,
	minecraft_guardian = 35,
	minecraft_hoglin = 36,
	minecraft_horse = 37,
	minecraft_husk = 38,
	minecraft_illusioner = 39,
	minecraft_iron_golem = 40,
	minecraft_item = 41,
	minecraft_item_frame = 42,
	minecraft_fireball = 43,
	minecraft_leash_knot = 44,
	minecraft_lightning_bolt = 45,
	minecraft_llama = 46,
	minecraft_llama_spit = 47,
	minecraft_magma_cube = 48,
	minecraft_marker = 49,
	minecraft_minecart = 50,
	minecraft_chest_minecart = 51,
	minecraft_command_block_minecart = 52,
	minecraft_furnace_minecart = 53,
	minecraft_hopper_minecart = 54,
	minecraft_spawner_minecart = 55,
	minecraft_tnt_minecart = 56,
	minecraft_mule = 57,
	minecraft_mooshroom = 58,
	minecraft_ocelot = 59,
	minecraft_painting = 60,
	minecraft_panda = 61,
	minecraft_parrot = 62,
	minecraft_phantom = 63,
	minecraft_pig = 64,
	minecraft_piglin = 65,
	minecraft_piglin_brute = 66,
	minecraft_pillager = 67,
	minecraft_polar_bear = 68,
	minecraft_tnt = 69,
	minecraft_pufferfish = 70,
	minecraft_rabbit = 71,
	minecraft_ravager = 72,
	minecraft_salmon = 73,
	minecraft_sheep = 74,
	minecraft_shulker = 75,
	minecraft_shulker_bullet = 76,
	minecraft_silverfish = 77,
	minecraft_skeleton = 78,
	minecraft_skeleton_horse = 79,
	minecraft_slime = 80,
	minecraft_small_fireball = 81,
	minecraft_snow_golem = 82,
	minecraft_snowball = 83,
	minecraft_spectral_arrow = 84,
	minecraft_spider = 85,
	minecraft_squid = 86,
	minecraft_stray = 87,
	minecraft_strider = 88,
	minecraft_egg = 89,
	minecraft_ender_pearl = 90,
	minecraft_experience_bottle = 91,
	minecraft_potion = 92,
	minecraft_trident = 93,
	minecraft_trader_llama = 94,
	minecraft_tropical_fish = 95,
	minecraft_turtle = 96,
	minecraft_vex = 97,
	minecraft_villager = 98,
	minecraft_vindicator = 99,
	minecraft_wandering_trader = 100,
	minecraft_witch = 101,
	minecraft_wither = 102,
	minecraft_wither_skeleton = 103,
	minecraft_wither_skull = 104,
	minecraft_wolf = 105,
	minecraft_zoglin = 106,
	minecraft_zombie = 107,
	minecraft_zombie_horse = 108,
	minecraft_zombie_villager = 109,
	minecraft_zombified_piglin = 110,
	minecraft_player = 111,
	minecraft_fishing_bobber = 112
};

enum PaintingMotive
{
	kebab,
	aztec,
	alban,
	aztec2,
	bomb,
	plant,
	wasteland,
	pool,
	courbet,
	sea,
	sunset,
	creebet,
	wanderer,
	graham,
	match,
	bust,
	stage,
	void_,
	skull_and_roses,
	wither,
	fighters,
	pointer,
	pigscene,
	burning_skull,
	skeleton,
	donkey_kong
};

class EntityProperty
{
public:
	mcString key;
	bdouble value;
	varInt nOfModifiers = 0;
	//modifier array

	SERVER_API EntityProperty(const mcString& key, double value);
};